from APIs.interfaces.requests.trigger_fannie_mae_web_posting_server_side_polling import \
    TriggerFannieMaeWebPostingServerSidePollingRequest


class TriggerFannieMaeXISServerSidePollingRequest(TriggerFannieMaeWebPostingServerSidePollingRequest):
    pass
