from dataclasses import dataclass, fields
from base.responses.base_response import BaseResponse, BaseListResponse


@dataclass
class GetFeesInfoKeys:
    FEE_ID: str = "FeeID"
    FEE_NUMBER: str = "FeeNumber"
    FEE_NAME: str = "FeeName"
    FEE_TYPE: str = "FeeType"
    LOAN_TYPES: str = "LoanTypes"
    PROPERTY_TYPES: str = "PropertyTypes"
    PROPERTY_CLASSIFICATION: str = "PropertyClassification"
    PUD_TYPES: str = "PUDTypes"
    FEE_PROGRAM_CATEGORIES: str = "FeeProgramCategories"
    LOAN_PURPOSES: str = "LoanPurposes"
    FINANCE_METHODS: str = "FinanceMethods"
    CAN_SHOP: str = "CanShop"
    FEE_FUNDING_TYPES: str = "FeeFundingTypes"
    STATE_LIST: str = "StateList"
    AUTO_ADD: str = "AutoAdd"
    POINTS_PERCENT: str = "PointsPercent"
    DAYS: str = "Days"
    AMOUNT: str = "Amount"
    TOTAL: str = "Total"
    MONTHS: str = "Months"
    AMOUNT_PER_YEAR: str = "AmountPerYear"
    POC: str = "POC"
    MEMO: str = "Memo"
    INCLUDE_APR: str = "IncludeAPR"
    UNDERWRITTEN_AREA: str = "UnderwrittenArea"
    BASED_ON: str = "BasedOn"
    FINANCE_FEE: str = "FinanceFee"
    PAID_TO: str = "PaidTo"
    PAID_TO_OTHER: str = "PaidToOther"
    PAID_BY: str = "PaidBy"
    PAID_BY_OTHER: str = "PaidByOther"
    SHOW_ON_GFE: str = "ShowOnGFE"
    SHOW_ON_HUD: str = "ShowOnHUD"
    ORIGINATION: str = "Origination"
    CAN_SELLER_PAY: str = "CanSellerPay"
    MONTHLY_HOUSING_LINK: str = "MonthlyHousingLink"
    SORT_FIELD: str = "SortField"
    PMI_MIP_FUNDING_FEE: str = "PMI_MIP_FundingFee"
    IMPOUND: str = "Impound"
    IMPOUND_MONTH_DUE: str = "ImpoundMonthDue"
    IMPOUND_MONTHS_DUE: str = "ImpoundMonthsDue"
    IMPOUND_FREQUENCY: str = "ImpoundFrequency"
    DAYS_PER_YEAR: str = "DaysPerYear"
    LINK_ESCROW_CUSHION: str = "LinkEscrowCushion"
    ESCROW_CUSHION: str = "EscrowCushion"
    IS_FEE_CURRENT: str = "IsFeeCurrent"
    IMPOUND_DATE_LINK: str = "ImpoundDateLink"
    EXPORT_LINK: str = "ExportLink"
    IMPOUND_EXPORT_LINK: str = "ImpoundExportLink"
    GMD_EXPORT_LINK: str = "GMDExportLink"
    COMPANY_LINKS: str = "CompanyLinks"
    NOTES: str = "Notes"
    DOC_MAGIC_EXPORT_LINK: str = "DocMagicExportLink"
    PROGRAM_LINKS: str = "ProgramLinks"
    WIRE_HOLD_BACK: str = "WireHoldBack"
    FEE_APP_INTELLIGENCE_HIGH_COST_LOAN_LINK: str = "FeeAppIntelligenceHighCostLoanLink"
    FEE_COMPLIANCE_EASE_LINK: str = "FeeComplianceEaseLink"
    FEE_EXTRA_DATA_LINKS: str = "FeeExtraDataLinks"
    FEE_MISMO_EXPORT_LINK: str = "FeeMISMOExportLink"
    HUD1_2010_LINE_NUMBER: str = "HUD12010LineNumber"
    LINK_FEE_ID: str = "LinkFeeId"
    CUSTOMARILY_PAID_BY_THE_BORROWER: str = "CustomarilyPaidByTheBorrower"
    LIEN_POSITIONS: str = "LienPositions"
    OCCUPANCIES: str = "Occupancies"
    BASED_ON_DATA_LANGUAGE: str = "BasedOnDataLanguage"
    FIS_EXPORT_LINK: str = "FISExportLink"
    ULDD_IMPOUND_EXPORT_LINK_ID: str = "ULDDImpoundExportLinkID"
    WORK_SHEET_203K: str = "WorkSheet203K"
    INSTANCE_COUNT: str = "InstanceCount"
    EFFECTIVE_START_DATE: str = "EffectiveStartDate"
    EFFECTIVE_END_DATE: str = "EffectiveEndDate"
    EFFECTIVE_DATE_NAME: str = "EffectiveDateName"
    FASB_COST: str = "FASBCost"
    FASB_CREDIT: str = "FASBCredit"
    INCLUDE_HIGH_COST_MORTGAGE_LOAN: str = "IncludeHighCostMortgageLoan"
    FEE_PAID_TO_AN_AFFILIATE: str = "FeePaidToAnAffiliate"
    SPLIT_ID: str = "SplitID"
    CE_FEE_CLASSIFICATION: str = "CEFeeClassification"
    BORROWER_SELECTED_SERVICE_PROVIDER: str = "BorrowerSelectedServiceProvider"
    SUBJECT_TO_TRID: str = "SubjectToTRID"
    LOAN_ESTIMATE_ADJUSTMENT: str = "LoanEstimateAdjustment"
    TRID_CHANGE_CATEGORY_OVERRIDE: str = "TRIDChangeCategoryOverride"
    FEE_IDS_DOCS_LINK: str = "FeeIDSDocsLink"
    FEE_MRG_DOCS_LINK: str = "FeeMRGDocsLink"
    IS_ACTIVE: str = "IsActive"
    SERVICING_ESCROW_CODE: str = "ServicingEscrowCode"
    SERVICING_ESCROW_CATEGORY: str = "ServicingEscrowCategory"
    CONSTRUCTION_MODIFICATION: str = "ConstructionModification"


@dataclass
class GetFeesKeys:
    FEES: str = "Fees"


class GetFees(BaseResponse):
    _ADD_KEYS = [field.default for field in fields(GetFeesInfoKeys)]


class GetFeesList(BaseListResponse):
    _SUB_MODEL = GetFees
