from dataclasses import dataclass, fields
from base.responses.base_response import BaseResponse, BaseListResponse


@dataclass
class CustomersInfoKeys:
    CUSTOMER_ID: str = "CustomerID"
    DECLARE_A: str = "DeclareA"
    DECLARE_B: str = "DeclareB"
    DECLARE_C: str = "DeclareC"
    DECLARE_D: str = "DeclareD"
    DECLARE_E: str = "DeclareE"
    DECLARE_F: str = "DeclareF"
    DECLARE_G: str = "DeclareG"
    DECLARE_H: str = "DeclareH"
    DECLARE_I: str = "DeclareI"
    DECLARE_J: str = "DeclareJ"
    DECLARE_K: str = "DeclareK"
    DECLARE_L: str = "DeclareL"
    DECLARE_M: str = "DeclareM"
    RACE_AMERICAN_ALASKA: str = "RaceAmericanAlaska"
    RACE_ASIAN: str = "RaceAsian"
    RACE_BLACK: str = "RaceBlack"
    RACE_HAWAIIAN_PACIFIC: str = "RaceHawaiianPacific"
    RACE_WHITE: str = "RaceWhite"
    ETHNICITY: str = "Ethnicity"
    SEX: str = "Sex"
    NOT_FURNISH_INFORMATION: str = "NotFurnishInformation"
    COBORROWER_INCOME_USED: str = "CoborrowerIncomeUsed"
    COMPLETED_JOINTLY: str = "CompletedJointly"
    DEPENDENTS_AGES: str = "DependentsAges"
    DEPENDENTS: str = "Dependents"
    MARITAL_STATUS: str = "MaritalStatus"
    APPLICATION_TAKEN_BY: str = "ApplicationTakenBy"
    APPLICATION_TAKEN_METHOD_TYPE: str = "ApplicationTakenMethodType"
    CREDIT_REPORT_AUTH: str = "CreditReportAuth"
    ALIMONY_OWED_TO: str = "AlimonyOwedTo"
    ALIMONY: str = "Alimony"
    ALIMONY_MONTHS_LEFT: str = "AlimonyMonthsLeft"
    CUSTOMER_FORECLOSURE_DATE: str = "CustomerForeclosureDate"
    PREVIOUS_ADDRESS_2: str = "PreviousAddress2"
    MAILING_ADDRESS_ID: str = "MailingAddressID"
    RACE_NOT_PROVIDED: str = "RaceNotProvided"
    RACE_NOT_APPLICABLE: str = "RaceNotApplicable"
    RACE_OTHER: str = "RaceOther"
    HMDA_GENDER_TYPE_MALE: str = "HMDAGenderTypeMale"
    HDMA_GENDER_TYPE_FEMALE: str = "HDMAGenderTypeFemale"
    HMDA_GENDER_REFUSAL_INDICATOR: str = "HMDAGenderRefusalIndicator"
    HMDA_GENDER_COLLECTED_BASED_ON_VISUAL_OBSERVATION_OR_NAME_INDICATOR: str = "HMDAGenderCollectedBasedOnVisualObservationOrNameIndicator"
    HMDA_ETHNICITY_TYPE_HISPANIC: str = "HMDAEthnicityTypeHispanic"
    HMDA_ETHNICITY_TYPE_NOT_HISPANIC: str = "HMDAEthnicityTypeNotHispanic"
    HMDA_ETHNICITY_ORIGIN_TYPE_CUBAN: str = "HMDAEthnicityOriginTypeCuban"
    HMDA_ETHNICITY_ORIGIN_TYPE_MEXICAN: str = "HMDAEthnicityOriginTypeMexican"
    HMDA_ETHNICITY_ORIGIN_TYPE_PUERTO_RICAN: str = "HMDAEthnicityOriginTypePuertoRican"
    HMDA_ETHNICITY_ORIGIN_TYPE_OTHER: str = "HMDAEthnicityOriginTypeOther"
    HMDA_ETHNICITY_ORIGIN_TYPE_OTHER_DESCRIPTION: str = "HMDAEthnicityOriginTypeOtherDescription"
    HMDA_ETHNICITY_REFUSAL_INDICATOR: str = "HMDAEthnicityRefusalIndicator"
    HMDA_ETHNICITY_COLLECTED_BASE_ON_VISUAL_OBSERVATION_OR_SURNAME_INDICATOR: str = "HMDAEthnicityCollectedBaseOnVisualObservationOrSurnameIndicator"
    HMDA_RACE_TRIBE: str = "HMDARaceTribe"
    HMDA_RACE_DESIGNATION_TYPE_ASIAN_INDIAN: str = "HMDARaceDesignationTypeAsianIndian"
    HMDA_RACE_DESIGNATION_TYPE_CHINESE: str = "HMDARaceDesignationTypeChinese"
    HMDA_RACE_DESIGNATION_TYPE_FILIPINO: str = "HMDARaceDesignationTypeFilipino"
    HMDA_RACE_DESIGNATION_TYPE_JAPANESE: str = "HMDARaceDesignationTypeJapanese"
    HMDA_RACE_DESIGNATION_TYPE_KOREAN: str = "HMDARaceDesignationTypeKorean"
    HMDA_RACE_DESIGNATION_TYPE_VIETNAMESE: str = "HMDARaceDesignationTypeVietnamese"
    HMDA_RACE_DESIGNATION_TYPE_OTHER_ASIAN: str = "HMDARaceDesignationTypeOtherAsian"
    HMDA_RACE_DESIGNATION_TYPE_OTHER_ASIAN_DESCRIPTION: str = "HMDARaceDesignationTypeOtherAsianDescription"
    HMDA_RACE_DESIGNATION_TYPE_HAWAIIAN: str = "HMDARaceDesignationTypeHawaiian"
    HMDA_RACE_DESIGNATION_TYPE_GUAMANIAN	: str = "HMDARaceDesignationTypeGuamanian"
    HMDA_RACE_DESIGNATION_TYPE_SAMOAN: str = "HMDARaceDesignationTypeSamoan"
    HMDA_RACE_DESIGNATION_TYPE_OTHER_PACIFIC_ISLANDER: str = "HMDARaceDesignationTypeOtherPacificIslander"
    HMDA_RACE_DESIGNATION_TYPE_OTHER_PACIFIC_ISLANDER_DESCRIPTION: str = "HMDARaceDesignationTypeOtherPacificIslanderDescription"
    HMDA_RACE_COLLECTED_BASED_ON_VISUAL_OBSERVATION_OR_SURNAME_INDICATOR: str = "HMDARaceCollectedBasedOnVisualObservationOrSurnameIndicator"
    CREDIT_REFERENCE_NUMBER: str = "CreditReferenceNumber"
    CREDIT_REFERENCE_DATE: str = "CreditReferenceDate"
    LAST_SHORT_SALE_DATE: str = "LastShortSaleDate"
    INTERVIEWED_BY: str = "InterviewedBy"
    INTERVIEW_EMPLOYEE_ID: str = "InterviewEmployeeID"
    INTERVIEW_COMPANY_ID: str = "InterviewCompanyID"
    PROPERTY_TYPE: str = "PropertyType"
    TITLE_HELD_AS: str = "TitleHeldAs"
    PREVIOUS_PROPERTY_FHA_SECONDARY_RESIDENCE: str = "PreviousPropertyFHASecondaryResidence"
    MILITARY_SERVICE_INDICATOR: str = "MilitaryServiceIndicator"
    MILITARY_ACTIVE_DUTY: str = "MilitaryActiveDuty"
    MILITARY_SERVICE_EXPECTED_COMPLETION_DATE: str = "MilitaryServiceExpectedCompletionDate"
    MILITARY_RETIRED: str = "MilitaryRetired"
    MILITARY_RESERVE_NATIONAL_GUARD_NEVER_ACTIVATED: str = "MilitaryReserveNationalGuardNeverActivated"
    MILITARY_SURVIVING_SPOUSE: str = "MilitarySurvivingSpouse"
    DOMESTIC_RELATIONSHIP_TYPE: str = "DomesticRelationshipType"
    DOMESTIC_RELATIONSHIP_TYPE_OTHER_DESCRIPTION: str = "DomesticRelationshipTypeOtherDescription"
    DOMESTIC_RELATIONSHIP_STATE_CODE: str = "DomesticRelationshipStateCode"
    DOMESTIC_RELATIONSHIP_INDICATOR: str = "DomesticRelationshipIndicator"
    SPECIAL_BORROWER_SELLER_RELATIONSHIP_INDICATOR: str = "SpecialBorrowerSellerRelationshipIndicator"
    UNDISCLOSED_BORROWED_FUNDS_AMOUNT: str = "UndisclosedBorrowedFundsAmount"
    UNDISCLOSED_MORTGAGE_APPLICATION_INDICATOR: str = "UndisclosedMortgageApplicationIndicator"
    UNDISCLOSED_CREDIT_APPLICATION_INDICATOR: str = "UndisclosedCreditApplicationIndicator"
    UNDISCLOSED_COMAKER_OF_NOTE_INDICATOR: str = "UndisclosedComakerOfNoteIndicator"
    PRIOR_PROPERTY_DEED_IN_LIEU_CONVEYED_INDICATOR: str = "PriorPropertyDeedInLieuConveyedIndicator"
    PRIOR_PROPERTY_SHORT_SALE_COMPLETED_INDICATOR: str = "PriorPropertyShortSaleCompletedIndicator"
    PRIOR_PROPERTY_FORECLOSURE_COMPLETED_INDICATOR: str = "PriorPropertyForeclosureCompletedIndicator"
    BANKRUPTCY_CHAPTER_TYPE_7: str = "BankruptcyChapterType7"
    BANKRUPTCY_CHAPTER_TYPE_11: str = "BankruptcyChapterType11"
    BANKRUPTCY_CHAPTER_TYPE_12: str = "BankruptcyChapterType12"
    BANKRUPTCY_CHAPTER_TYPE_13: str = "BankruptcyChapterType13"
    NON_PERMANENT_RESIDENT_ALIEN: str = "NonPermanentResidentAlien"
    NON_RESIDENT_ALIEN: str = "NonResidentAlien"
    DOMESTIC_RELATIONSHIP_PRINT_INDICATOR: str = "DomesticRelationshipPrintIndicator"
    CREDIT_REFERENCE_VENDOR: str = "CreditReferenceVendor"
    NOTES_FOR_1003: str = "NotesFor1003"


@dataclass
class CustomersKeys:
    CUSTOMERS: str = "Customers"

class Customer(BaseResponse):
    _ADD_KEYS = [field.default for field in fields(CustomersInfoKeys)]

class Customers(BaseListResponse):
    _SUB_MODEL = Customer

